[features]
seeds = false
skip-lint = false
[programs.localnet]
anchorcalculator = "A2E5Gp2ijYhf1F8QRQK5m37PMojef2tsZqTvApS3G6P2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/aron/recover/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
